#!/bin/bash -ex

REPO="codeigniter4/CodeIgniter4"
VERSION="$(gh_releases $REPO)"
URL="https://github.com/$REPO/archive/v${VERSION}.zip"

[ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
curl -L -f $PROXY $URL -o /usr/local/src/codeigniter.zip
