#!/bin/bash -ex

VERSION="4.0.3.zip"
URL="https://github.com/codeigniter4/CodeIgniter4/archive/$VERSION"

[ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
curl -L -f $PROXY $URL -o /usr/local/src/codeigniter.zip

