#!/bin/sh -ex

DB_NAME=codeigniter
DB_USER=codeigniter
DB_PASS=$(mcookie)

SRC=/usr/local/src
WEBROOT=/var/www/codeigniter
CI=/var/local/codeigniter

# unpack and configure
unzip $SRC/codeigniter.zip -d $SRC
mv $SRC/CodeIgniter* $WEBROOT
rm $SRC/codeigniter.zip
chown -R root:root $WEBROOT

mkdir -p $CI
mv $WEBROOT/app $CI
mv $WEBROOT/system $CI
mv $WEBROOT/writable $CI
mv $WEBROOT/env $CI/.env

CONF=$CI/app/Config/Paths.php
sed -i "s|\$systemDirectory = __DIR__ \. '/../../system';|\$systemDirectory = '$CI/system';|" $CONF
sed -i "s|\$appDirectory = __DIR__ \. '/..';|\$appDirectory = '$CI/app';|" $CONF

CONF=$CI/app/Views/welcome_message.php
sed -i 's|app/Views|/var/local/codeigniter/app/Views|' $CONF
sed -i 's|app/Controllers|/var/local/codeigniter/app/Controllers|' $CONF
sed -i '/CONTENT -->/,/<div/ s|</section>|<?php include '"'"'_tkl_include.php'"'"';?></section>|' $CONF

mkdir -p $WEBROOT/public/assets

cp -TdR $SRC/codeigniter.overlay $CI
rm -rf $SRC/codeigniter.overlay

# configure apache
a2dissite 000-default
a2ensite codeigniter
a2enmod rewrite

# setup the database
service mysql start

MYSQL_BATCH="mysql --user=root --password=$MYSQL_PASS --batch"
MYSQL_ADMIN="mysqladmin --user=root --password=$MYSQL_PASS"

$MYSQL_ADMIN create $DB_NAME
$MYSQL_BATCH --execute "grant all privileges on $DB_NAME.* to $DB_USER@localhost identified by '$DB_PASS'; flush privileges;"

CONF=$CI/app/Config/Database.php
sed -i "/public \$default = \[/,/    \];/ s|'username' => .*|'username' => '$DB_USER',|" $CONF
sed -i "/public \$default = \[/,/    \];/ s|'password' => .*|'password' => '$DB_PASS',|" $CONF
sed -i "/public \$default = \[/,/    \];/ s|'database' => .*|'database' => '$DB_NAME',|" $CONF

service mysql stop

# misc tweak and secure configuration files from prying eyes
CONF=$CI/app/Config/Encryption.php
sed -i "s|public \$key = .*|public \$key = '$(mcookie)';|" $CONF

CONF=$WEBROOT/public/index.php
sed -i "/^require realpath(FCPATH/ s|^.*$|require realpath(FCPATH . '../../../local/codeigniter/app/Config/Paths.php') ?: FCPATH . '../app/Config/Paths.php';|" /var/www/codeigniter/public/index.php

chown -R www-data:www-data $CI/app/Config
chmod 640 $CI/app/Config/*.php
chown -R www-data:www-data $CI/writable
