#!/bin/sh -ex

DB_NAME=codeigniter
DB_USER=codeigniter
DB_PASS=$(mcookie)

SRC=/usr/local/src
WEBROOT=/var/www/codeigniter
CI=/var/local/codeigniter

# unpack and configure
unzip $SRC/CodeIgniter_*.zip -d $(dirname $WEBROOT)
mv $(dirname $WEBROOT)/CodeIgniter_* $WEBROOT
rm $SRC/CodeIgniter_*.zip
chown -R root:root $WEBROOT

mkdir -p $CI
mv $WEBROOT/application $CI
mv $WEBROOT/system $CI

CONF=$WEBROOT/index.php
sed -i "s|\$system_path = 'system';|\$system_path = '$CI/system';|" $CONF
sed -i "s|\$application_folder = 'application';|\$application_folder = '$CI/application';|" $CONF

# setup tkl-webcp
CONF=$CI/application/config/routes.php
sed -i "s|^\$route\['default.*|\$route['default_controller'] = \"tklwebcp\";|" $CONF

mkdir -p $WEBROOT/assets
mv /var/www/js $WEBROOT/assets
mv /var/www/css $WEBROOT/assets
mv /var/www/images $WEBROOT/assets

cp -TdR $SRC/codeigniter.overlay $CI
rm -rf $SRC/codeigniter.overlay

# configure apache
a2dissite default
a2ensite codeigniter
a2enmod rewrite

# setup the database
/etc/init.d/mysql start

MYSQL_BATCH="mysql --user=root --password=$MYSQL_PASS --batch"
MYSQL_ADMIN="mysqladmin --user=root --password=$MYSQL_PASS"

$MYSQL_ADMIN create $DB_NAME
$MYSQL_BATCH --execute "grant all privileges on $DB_NAME.* to $DB_USER@localhost identified by '$DB_PASS'; flush privileges;"

CONF=$CI/application/config/database.php
sed -i "s|default'\]\['username.*|default']['username'] = '$DB_USER';|" $CONF
sed -i "s|default'\]\['password.*|default']['password'] = '$DB_PASS';|" $CONF
sed -i "s|default'\]\['database.*|default']['database'] = '$DB_NAME';|" $CONF

/etc/init.d/mysql stop

# misc tweak and secure configuration files from prying eyes
CONF=$CI/application/config/config.php
sed -i "s|encryption_key.*|encryption_key'] = '$(mcookie)';|" $CONF

chown -R www-data:www-data $CI/application/config
chmod 640 $CI/application/config/*.php

