#!/bin/bash -e
# regenerate codeigniter secrets and mysql password

. /etc/default/inithooks

ENCKEY=$(mcookie)
PASSWORD=$(mcookie)

CONF=/var/local/codeigniter/app/Config/Encryption.php
sed -i "s|public key.*|public key = '$ENCKEY';|" $CONF

CONF=/var/local/codeigniter/app/Config/Database.php
sed -i "/public \$default = \[/,/\];/ s|'password' => .*|'password' => '$PASSWORD',|" $CONF
$INITHOOKS_PATH/bin/mysqlconf.py --user=codeigniter --pass="$PASSWORD"

