#!/bin/bash -e
# regenerate codeigniter secrets and mysql password

. /etc/default/inithooks

ENCKEY=$(mcookie)
PASSWORD=$(mcookie)

CONF=/var/local/codeigniter/application/config/config.php
sed -i "s|encryption_key.*|encryption_key'] = '$ENCKEY';|" $CONF

CONF=/var/local/codeigniter/application/config/database.php
sed -i "s|default'\]\['password.*|default']['password'] = '$PASSWORD';|" $CONF
$INITHOOKS_PATH/bin/mysqlconf.py --user=codeigniter --pass="$PASSWORD"

